"""Compatibility facade for checkpoint lifecycle hook requests."""

from __future__ import annotations

from weiss_rl.training.train_entrypoint.checkpoint_lifecycle_hooks import (
    BuildCheckpointRecordRequest,
    BuildHeuristicPublicPolicyRequest,
    BuildTrainingLearnerRequest,
    EnsureNoLeagueBaselineAnchorRequest,
    ImportNoLeagueBaselineAnchorRequest,
    ImportSeedSnapshotPoolRequest,
    InitializeLearnerCheckpointRequest,
    LoadSnapshotEvalModelRequest,
    PublishCheckpointAliasesRequest,
    RestoreLearnerCheckpointRequest,
    SeedSnapshotPolicyIdRequest,
    StructuredWarmstartRequest,
    ValidateSeedSnapshotImportContractRequest,
    WriteCheckpointRequest,
    build_checkpoint_record_with_entrypoint_hooks,
    build_heuristic_public_policy_with_entrypoint_hooks,
    build_training_learner_with_entrypoint_hooks,
    ensure_noleague_baseline_anchor_with_entrypoint_hooks,
    import_noleague_baseline_anchor_with_entrypoint_hooks,
    import_seed_snapshot_pool_with_entrypoint_hooks,
    initialize_learner_from_checkpoint_with_entrypoint_hooks,
    load_snapshot_eval_model_with_entrypoint_hooks,
    publish_checkpoint_aliases_with_entrypoint_hooks,
    restore_learner_from_checkpoint_with_entrypoint_hooks,
    run_structured_warmstart_with_entrypoint_hooks,
    seed_snapshot_policy_id_with_entrypoint_hooks,
    validate_seed_snapshot_import_contract_with_entrypoint_hooks,
    write_checkpoint_with_entrypoint_hooks,
)

__all__ = [
    "BuildCheckpointRecordRequest",
    "BuildHeuristicPublicPolicyRequest",
    "BuildTrainingLearnerRequest",
    "EnsureNoLeagueBaselineAnchorRequest",
    "ImportNoLeagueBaselineAnchorRequest",
    "ImportSeedSnapshotPoolRequest",
    "InitializeLearnerCheckpointRequest",
    "LoadSnapshotEvalModelRequest",
    "PublishCheckpointAliasesRequest",
    "RestoreLearnerCheckpointRequest",
    "SeedSnapshotPolicyIdRequest",
    "StructuredWarmstartRequest",
    "ValidateSeedSnapshotImportContractRequest",
    "WriteCheckpointRequest",
    "build_checkpoint_record_with_entrypoint_hooks",
    "build_heuristic_public_policy_with_entrypoint_hooks",
    "build_training_learner_with_entrypoint_hooks",
    "ensure_noleague_baseline_anchor_with_entrypoint_hooks",
    "import_noleague_baseline_anchor_with_entrypoint_hooks",
    "import_seed_snapshot_pool_with_entrypoint_hooks",
    "initialize_learner_from_checkpoint_with_entrypoint_hooks",
    "load_snapshot_eval_model_with_entrypoint_hooks",
    "publish_checkpoint_aliases_with_entrypoint_hooks",
    "restore_learner_from_checkpoint_with_entrypoint_hooks",
    "run_structured_warmstart_with_entrypoint_hooks",
    "seed_snapshot_policy_id_with_entrypoint_hooks",
    "validate_seed_snapshot_import_contract_with_entrypoint_hooks",
    "write_checkpoint_with_entrypoint_hooks",
]
