"""Training orchestration helpers.

The canonical training CLI is ``python -m weiss_rl.training.train_entrypoint``.
"""

from importlib import import_module

from .algorithm_contracts import validate_algorithm_model_contract
from .algorithm_families import (
    IMPALA_ALGORITHMS,
    PPO_ALGORITHMS,
    STRUCTURED_VTRACE_ALGORITHMS,
    training_algorithm_family,
)
from .batches import (
    MinimalRollout,
    bootstrap_values,
    build_learner_batch,
    collect_training_batch,
)
from .checkpointing.guard import (
    checkpoint_candidate_metric,
    confirmatory_dev_eval_request,
    confirmatory_dev_eval_target_pairs,
    dev_eval_aggregate_score,
    dev_eval_confidence_stats,
    dev_eval_ineligibility_reasons,
    dev_eval_metric_eligible,
    dev_eval_worst_natural_timeout_rate,
    dev_eval_worst_no_progress_timeout_rate,
    dev_eval_worst_reason_rate,
    dev_eval_worst_stall_rate,
    dev_eval_worst_truncation_rate,
    expand_periodic_dev_eval_paired_seeds,
    should_promote_best_checkpoint,
    summary_rate,
)
from .checkpoints import (
    BEST_CHECKPOINT_FILENAME,
    CHECKPOINT_TRACKER_FILENAME,
    LATEST_CHECKPOINT_FILENAME,
    MINIMAL_TRAIN_CHECKPOINT_FORMAT,
    OBSERVED_BEST_CHECKPOINT_FILENAME,
    CheckpointPayloadContract,
    ResumeCheckpoint,
    append_checkpoint_guard_event,
    best_checkpoint_record,
    build_checkpoint_record,
    build_minimal_train_checkpoint_payload,
    checkpoint_guard_log_path,
    checkpoint_path_for_update,
    current_focal_policy_id,
    ensure_current_checkpoint,
    extract_structured_guard_b2_anchor_score,
    initialize_model_from_checkpoint,
    load_checkpoint_tracker,
    maybe_finalize_from_best_checkpoint,
    maybe_log_structured_mainmove_guard,
    maybe_rollback_to_best_checkpoint,
    observed_best_checkpoint_path,
    publish_checkpoint_aliases,
    resolve_resume_checkpoint_path,
    restore_minimal_train_checkpoint,
    validate_checkpoint_payload_contract,
    write_checkpoint_tracker,
    write_minimal_train_checkpoint,
    write_scalars_record,
)
from .cli import build_train_parser
from .dev_eval import (
    evaluation_config_or_raise,
    json_relative_path,
    legal_ids_for_env_row,
    periodic_dev_eval_bootstrap_seed,
    periodic_dev_eval_rng_seed,
    periodic_dev_eval_schedule,
    periodic_dev_eval_seed_usage_payload,
    periodic_dev_eval_summaries_path,
    persist_periodic_dev_eval_summary,
    promotion_gate_bootstrap_seed,
    promotion_gate_rng_seed,
    resolve_periodic_dev_eval_seed_file,
    resolve_repo_path,
    should_run_periodic_dev_eval,
    stall_monitor_state_path,
    update_stall_monitor,
    validate_periodic_dev_eval_contract,
    write_json,
)
from .environments import (
    build_ids_eval_env,
    build_training_env,
    env_pool_config,
    spec_dimensions,
)
from .guidance import (
    apply_guidance_schedule_for_next_update,
    entropy_coef_for_next_update,
    model_guidance_payload,
    public_heuristic_logit_bias_scale_for_next_update,
    restore_model_guidance_from_payload,
    teacher_public_heuristic_coef_for_next_update,
)
from .inputs import (
    expected_sha256,
    normalize_sha256,
    require_matching_hash,
    require_positive_int,
    resolve_run_label,
    spec_mismatch_policy,
)
from .learner_factory import build_training_learner
from .manifest_layout import hardware_actor_layout_payload, manifest_actor_device_layout
from .paths import TrainingPaths, run_artifacts_from_existing_run_dir, training_paths
from .profiling import build_training_profiler, profile_block
from .promotion import (
    build_heuristic_public_policy,
    find_noleague_baseline_snapshot,
    promotion_anchor_policy_id_candidates,
    resolve_promotion_anchor_policy_ids,
    resolve_symbolic_promotion_anchor_policy_id,
    slug_policy_id,
    snapshot_meta_by_policy_id,
)
from .snapshots import (
    delete_pruned_snapshot_artifacts,
    demote_registry_champions_newer_than,
    persist_snapshot_registry_entry,
    save_snapshot_registry_with_retention,
    seed_snapshot_policy_id,
    sha256_file,
    snapshot_artifact_dir_for_prune,
    sync_snapshot_registry_retention,
    write_imported_snapshot_artifact,
    write_json_file,
    write_snapshot_artifact,
)
from .startup import (
    apply_training_flag_overrides,
    manifest_scaffold_only_reason,
    noleague_training_prerequisite_failure,
    print_manifest_only_message,
    raise_noleague_training_prerequisite_failure,
    raise_runtime_prerequisite_failure,
    resolve_device,
    resolve_runtime_profile,
    resolve_seed,
    runtime_training_prerequisite_failure,
)
from .torch_threads import (
    central_runtime_actor_torch_threads,
    configure_torch_threads,
    torch_num_threads_scope,
)
from .warmstart import run_structured_warmstart

_TRAIN_ENTRYPOINT_MODULES = frozenset(
    {
        "checkpoints",
        "cli",
        "compat",
        "core_exports",
        "eval_exports",
        "lifecycle",
        "metadata_hooks",
        "metadata_wrappers",
        "runner_hooks",
        "runner_wrappers",
        "snapshots",
        "training_exports",
        "wrappers",
    }
)

_CHECKPOINTING_MODULES = frozenset(
    {
        "alias_candidates",
        "alias_mutation",
        "alias_publication",
        "aliases",
        "finalization",
        "guard_events",
        "guard",
        "interpolation_cli",
        "interpolation_entrypoint",
        "interpolation_reporting",
        "interpolation_runtime",
        "interpolation",
        "io",
        "lifecycle_decisions",
        "lifecycle_effects",
        "lifecycle_plans",
        "lifecycle_transitions",
        "lifecycle",
        "load",
        "periodic_dev_eval_confirmatory",
        "periodic_dev_eval_guard",
        "periodic_dev_eval",
        "publish_cli",
        "publish_entrypoint",
        "publish_reporting",
        "publish_runtime",
        "publish",
        "resolution",
        "restore_state",
        "restore",
        "snapshot_promotion",
        "structured_guard",
        "tracker",
        "write",
    }
)

_LEGACY_TRAINING_MODULES = {
    "dev_eval_opponents": "dev_eval.opponents",
    "dev_eval_runner": "dev_eval.runner",
    "minimal_dev_eval": "minimal.dev_eval",
    "minimal_entrypoint_hooks": "minimal.entrypoint_hooks",
    "minimal_finalization": "minimal.finalization",
    "minimal_hook_groups": "minimal.hook_groups",
    "minimal_initialization": "minimal.initialization",
    "minimal_loop": "minimal.loop",
    "minimal_promotion": "minimal.promotion",
    "minimal_runner": "minimal.runner",
    "minimal_setup": "minimal.setup",
    "minimal_update": "minimal.update",
    "paired_auxiliary_replay": "replay_data.paired_auxiliary_replay",
    "paired_outcome_preference_dataset": "replay_data.paired_outcome_preference_dataset",
    "paired_outcome_preference_replay": "replay_data.paired_outcome_preference_replay",
    "paired_outcome_preference_warmstart_cli": "warmstarts.paired_outcome_preference_warmstart_cli",
    "paired_outcome_preference_warmstart_entrypoint": "warmstarts.paired_outcome_preference_warmstart_entrypoint",
    "paired_outcome_preference_warmstart_runtime": "warmstarts.paired_outcome_preference_warmstart_runtime",
    "paired_outcome_preference_warmstart_support": "warmstarts.paired_outcome_preference_warmstart_support",
    "paired_swing_conflict_filter": "replay_data.paired_swing_conflict_filter",
    "paired_swing_replay": "replay_data.paired_swing_replay",
    "paired_swing_warmstart_cli": "warmstarts.paired_swing_warmstart_cli",
    "paired_swing_warmstart_entrypoint": "warmstarts.paired_swing_warmstart_entrypoint",
    "paired_swing_warmstart_runtime": "warmstarts.paired_swing_warmstart_runtime",
    "training_loop_progress": "loop.loop_progress",
    "training_post_update": "loop.post_update",
    "training_replay_dispatch": "replay_data.training_replay_dispatch",
    "training_replay_paths": "replay_data.training_replay_paths",
    "training_replay_states": "replay_data.training_replay_states",
    "training_run_contexts": "loop.run_contexts",
    "training_runner": "loop.runner",
    "training_setup": "loop.setup",
    "training_update": "loop.update",
    "training_update_batch": "loop.update_batch",
    "training_update_completion": "loop.update_completion",
    "training_update_phases": "loop.update_phases",
    "training_update_schedule": "loop.update_schedule",
    "training_update_stage_pipeline": "loop.update_stage_pipeline",
    "training_update_step": "loop.update_step",
    "trajectory_bc_replay": "replay_data.trajectory_bc_replay",
    "trajectory_bc_sampling": "replay_data.trajectory_bc_sampling",
    "trajectory_bc_teacher_state": "replay_data.trajectory_bc_teacher_state",
    "trajectory_bc_warmstart_cli": "warmstarts.trajectory_bc_warmstart_cli",
    "trajectory_bc_warmstart_entrypoint": "warmstarts.trajectory_bc_warmstart_entrypoint",
    "trajectory_bc_warmstart_runtime": "warmstarts.trajectory_bc_warmstart_runtime",
    "warmstart_artifacts": "warmstarts.warmstart_artifacts",
    "warmstart_replay_support": "warmstarts.warmstart_replay_support",
}


def __getattr__(name: str):
    train_prefix = "train_entrypoint_"
    if name.startswith(train_prefix):
        suffix = name.removeprefix(train_prefix)
        if suffix in _TRAIN_ENTRYPOINT_MODULES:
            module = import_module(f".train_entrypoint.{suffix}", __name__)
            globals()[name] = module
            return module
    checkpoint_prefix = "checkpoint_"
    if name.startswith(checkpoint_prefix):
        suffix = name.removeprefix(checkpoint_prefix)
        if suffix in _CHECKPOINTING_MODULES:
            module = import_module(f".checkpointing.{suffix}", __name__)
            globals()[name] = module
            return module
    if name in _LEGACY_TRAINING_MODULES:
        module = import_module(f".{_LEGACY_TRAINING_MODULES[name]}", __name__)
        globals()[name] = module
        return module
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "BEST_CHECKPOINT_FILENAME",
    "CHECKPOINT_TRACKER_FILENAME",
    "IMPALA_ALGORITHMS",
    "CheckpointPayloadContract",
    "LATEST_CHECKPOINT_FILENAME",
    "MINIMAL_TRAIN_CHECKPOINT_FORMAT",
    "OBSERVED_BEST_CHECKPOINT_FILENAME",
    "MinimalRollout",
    "PPO_ALGORITHMS",
    "ResumeCheckpoint",
    "STRUCTURED_VTRACE_ALGORITHMS",
    "TrainingPaths",
    "append_checkpoint_guard_event",
    "best_checkpoint_record",
    "bootstrap_values",
    "build_checkpoint_record",
    "build_heuristic_public_policy",
    "build_ids_eval_env",
    "build_learner_batch",
    "build_minimal_train_checkpoint_payload",
    "build_train_parser",
    "build_training_env",
    "build_training_learner",
    "build_training_profiler",
    "checkpoint_candidate_metric",
    "checkpoint_guard_log_path",
    "checkpoint_path_for_update",
    "central_runtime_actor_torch_threads",
    "configure_torch_threads",
    "collect_training_batch",
    "confirmatory_dev_eval_request",
    "confirmatory_dev_eval_target_pairs",
    "current_focal_policy_id",
    "dev_eval_aggregate_score",
    "dev_eval_confidence_stats",
    "dev_eval_ineligibility_reasons",
    "dev_eval_metric_eligible",
    "dev_eval_worst_natural_timeout_rate",
    "dev_eval_worst_no_progress_timeout_rate",
    "dev_eval_worst_reason_rate",
    "dev_eval_worst_stall_rate",
    "dev_eval_worst_truncation_rate",
    "expand_periodic_dev_eval_paired_seeds",
    "expected_sha256",
    "extract_structured_guard_b2_anchor_score",
    "delete_pruned_snapshot_artifacts",
    "demote_registry_champions_newer_than",
    "entropy_coef_for_next_update",
    "env_pool_config",
    "ensure_current_checkpoint",
    "evaluation_config_or_raise",
    "find_noleague_baseline_snapshot",
    "apply_guidance_schedule_for_next_update",
    "apply_training_flag_overrides",
    "json_relative_path",
    "legal_ids_for_env_row",
    "load_checkpoint_tracker",
    "model_guidance_payload",
    "manifest_scaffold_only_reason",
    "manifest_actor_device_layout",
    "hardware_actor_layout_payload",
    "maybe_finalize_from_best_checkpoint",
    "maybe_log_structured_mainmove_guard",
    "maybe_rollback_to_best_checkpoint",
    "normalize_sha256",
    "noleague_training_prerequisite_failure",
    "persist_snapshot_registry_entry",
    "periodic_dev_eval_bootstrap_seed",
    "periodic_dev_eval_rng_seed",
    "periodic_dev_eval_schedule",
    "periodic_dev_eval_seed_usage_payload",
    "periodic_dev_eval_summaries_path",
    "persist_periodic_dev_eval_summary",
    "observed_best_checkpoint_path",
    "print_manifest_only_message",
    "profile_block",
    "promotion_gate_bootstrap_seed",
    "promotion_gate_rng_seed",
    "promotion_anchor_policy_id_candidates",
    "publish_checkpoint_aliases",
    "public_heuristic_logit_bias_scale_for_next_update",
    "raise_noleague_training_prerequisite_failure",
    "raise_runtime_prerequisite_failure",
    "require_matching_hash",
    "require_positive_int",
    "resolve_device",
    "resolve_periodic_dev_eval_seed_file",
    "resolve_promotion_anchor_policy_ids",
    "resolve_resume_checkpoint_path",
    "resolve_repo_path",
    "resolve_run_label",
    "resolve_symbolic_promotion_anchor_policy_id",
    "resolve_runtime_profile",
    "resolve_seed",
    "restore_model_guidance_from_payload",
    "restore_minimal_train_checkpoint",
    "initialize_model_from_checkpoint",
    "run_artifacts_from_existing_run_dir",
    "run_structured_warmstart",
    "runtime_training_prerequisite_failure",
    "save_snapshot_registry_with_retention",
    "seed_snapshot_policy_id",
    "sha256_file",
    "should_run_periodic_dev_eval",
    "should_promote_best_checkpoint",
    "snapshot_artifact_dir_for_prune",
    "snapshot_meta_by_policy_id",
    "slug_policy_id",
    "spec_mismatch_policy",
    "spec_dimensions",
    "stall_monitor_state_path",
    "summary_rate",
    "sync_snapshot_registry_retention",
    "teacher_public_heuristic_coef_for_next_update",
    "torch_num_threads_scope",
    "training_algorithm_family",
    "training_paths",
    "update_stall_monitor",
    "validate_checkpoint_payload_contract",
    "validate_algorithm_model_contract",
    "validate_periodic_dev_eval_contract",
    "write_imported_snapshot_artifact",
    "write_json_file",
    "write_json",
    "write_checkpoint_tracker",
    "write_minimal_train_checkpoint",
    "write_scalars_record",
    "write_snapshot_artifact",
]
