"""Training, checkpoint, and snapshot legacy aliases for the entrypoint facade."""

from __future__ import annotations

from collections.abc import Mapping

TRAINING_NAMESPACE_ALIASES: Mapping[str, str] = {
    "MinimalRollout": "_TrainingMinimalRollout",
    "_LATEST_CHECKPOINT_FILENAME": "LATEST_CHECKPOINT_FILENAME",
    "_BEST_CHECKPOINT_FILENAME": "BEST_CHECKPOINT_FILENAME",
    "_CHECKPOINT_TRACKER_FILENAME": "CHECKPOINT_TRACKER_FILENAME",
    "_IMPALA_ALGORITHMS": "IMPALA_ALGORITHMS",
    "_PPO_ALGORITHMS": "PPO_ALGORITHMS",
    "_append_checkpoint_guard_event": "append_checkpoint_guard_event",
    "_assert_noleague_baseline_config": "assert_noleague_baseline_config",
    "_best_checkpoint_record": "best_checkpoint_record",
    "_bootstrap_values": "bootstrap_values",
    "_build_learner_batch": "build_learner_batch",
    "_canonical_config_sections": "canonical_config_sections",
    "_central_runtime_actor_torch_threads": "central_runtime_actor_torch_threads",
    "_checkpoint_guard_log_path": "checkpoint_guard_log_path",
    "_config_marks_noleague_baseline": "config_marks_noleague_baseline",
    "_configure_torch_threads": "configure_torch_threads",
    "_delete_pruned_snapshot_artifacts": "delete_pruned_snapshot_artifacts",
    "_demote_registry_champions_newer_than": "demote_registry_champions_newer_than",
    "_evaluation_pinning": "evaluation_pinning",
    "_extract_structured_guard_b2_anchor_score": "extract_structured_guard_b2_anchor_score",
    "_is_noleague_baseline_role": "is_noleague_baseline_role",
    "_legacy_noleague_baseline_mode": "legacy_noleague_baseline_mode",
    "_load_checkpoint_tracker": "load_checkpoint_tracker",
    "_load_json_object": "load_json_object",
    "_manifest_actor_device_layout": "manifest_actor_device_layout",
    "_manifest_source_path": "manifest_source_path",
    "_maybe_log_structured_mainmove_guard": "maybe_log_structured_mainmove_guard",
    "_read_optional_hash_file": "read_optional_hash_file",
    "_relative_path_text": "relative_path_text",
    "_resolve_resume_checkpoint_path": "resolve_resume_checkpoint_path",
    "_role_from_config_canonical": "role_from_config_canonical",
    "_run_artifacts_from_existing_run_dir": "run_artifacts_from_existing_run_dir",
    "_save_snapshot_registry_with_retention": "save_snapshot_registry_with_retention",
    "_sha256_file": "sha256_file",
    "_snapshot_artifact_dir_for_prune": "snapshot_artifact_dir_for_prune",
    "_start_nonce": "start_nonce",
    "_sync_snapshot_registry_retention": "sync_snapshot_registry_retention",
    "_torch_num_threads_scope": "torch_num_threads_scope",
    "_training_paths": "_training_paths_impl",
    "_validate_imported_snapshot_contract": "validate_imported_snapshot_contract",
    "_write_checkpoint_tracker": "write_checkpoint_tracker",
    "_write_json_file": "write_json_file",
    "_write_scalars_record": "write_scalars_record",
    "_write_snapshot_artifact": "write_snapshot_artifact",
    "_hardware_summary": "hardware_summary",
    "_entropy_coef_for_next_update": "entropy_coef_for_next_update",
    "_teacher_public_heuristic_coef_for_next_update": "teacher_public_heuristic_coef_for_next_update",
    "_public_heuristic_logit_bias_scale_for_next_update": "public_heuristic_logit_bias_scale_for_next_update",
    "_apply_guidance_schedule_for_next_update": "apply_guidance_schedule_for_next_update",
    "_model_guidance_payload": "model_guidance_payload",
    "_restore_model_guidance_from_payload": "restore_model_guidance_from_payload",
    "_maybe_compile_learner_model": "maybe_compile_learner_model",
    "_validate_algorithm_model_contract": "validate_algorithm_model_contract",
}
